config/routes.rb
Rails.application.routes.draw do
  # path: '' so that it won't show as /users/login but as /login
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'rails-projects', to: 'portfolios#rails'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :change_status
    end
  end
  root 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  belongs_to :category, optional: true
  friendly_id :title, use: :slugged

  enum status: { draft: 0, published: 1}

  validates_presence_of :title, :body
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :change_status]
  access all: [:show, :index], user: {except: [:destroy, :new, :edit, :create, :update, :change_status]}, admin: :all
  layout "blog"

  # GET /blogs
  # GET /blogs.json
  def index
    # kaminari/pagination gem
    @blogs = Blog.page(params[:page]).per(5)
    @page_title = "Other-side.net | Blog"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @page_title = @blog.title
    @seo_keywords = @blog.body
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog post was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def change_status
    if @blog.draft?
      @blog.published!
      respond_to do |format|
        format.html { redirect_to blogs_url, notice: "Blog entry status was updated from 'draft' to 'published'" }
      end
    else
      @blog.draft!
      respond_to do |format|
        format.html { redirect_to blogs_url, notice: "Blog entry status was updated from 'published' to 'draft'" }
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body, :categories)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h2>
<p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago (<%= blog.created_at.to_date %>) by <%= current_user.first_name %></p>
<p class="blog-post-meta">
<% if logged_in?(:admin) %>
  <%= link_to blog.status.capitalize, change_status_blog_path(blog) %> /
  <%= link_to 'Edit', edit_blog_path(blog) %> /
  <%= link_to 'Delete entry', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
</p>
<p>  <%= blog.body %> </p>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control', rows: 30  %>
  </div>

  <div class="form-group">
    <%= form.submit class: 'btn btn-outline-primary'%>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="blog-post">  

  <h1>Editing <%= @blog.title %></h1>

  <%= render 'form', blog: @blog if logged_in?(:admin) %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div class="blog-post">
  <%= paginate @blogs %>
  
  <%= render @blogs %>
</div>

<%= paginate @blogs %>

app/views/blogs/new.html.erb
<div class="blog-post">

<h1>New Blog</h1>

<%= render 'form', blog: @blog if logged_in?(:admin) %>

<%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/show.html.erb
<div class="blog-post">

  <h1><%= @blog.title %></h1>
  <%= link_to 'Edit', edit_blog_path(@blog) if logged_in?(:admin) %>

  <p><%= @blog.body %></p>

</div>