config/routes.rb
Rails.application.routes.draw do
  # path: '' so that it won't show as /users/login but as /login
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'rails-projects', to: 'portfolios#rails'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :change_status
    end
  end
  root 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord

  has_many :technologies, dependent: :destroy
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  validates_presence_of :title, :body

  scope :rails, -> { (where(subtitle: 'Rails')) }
  scope :react, -> { (where(subtitle: 'React')) }
  scope :by_position, -> { (order("position ASC")) }

  mount_uploader :thumbnail, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:edit, :update, :show, :destroy]
  access all: [:show, :index, :react, :rails], user: {except: [:destroy, :new, :edit, :create, :update, :sort]}, admin: :all

  layout "portfolio"

  def index
    @portfolio_items = Portfolio.by_position
  end

  def react
    @react_items = Portfolio.react
  end

  def rails
    @rails_items = Portfolio.rails
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render body: nil #bypass render No template found, we don't need a view
  end

  def new
    @portfolio_item = Portfolio.new
    # refactor later w/ JS to add another item check box/similar feature:
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)
    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'A project was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html {redirect_to portfolios_path, notice: 'Project item was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
  end

  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Project item was successfully deleted.' }
    end
  end

  private
  def set_portfolio
    @portfolio_item = Portfolio.find(params[:id])
  end

  # to allow attrs/whitelisting
  def portfolio_params
    params.require(:portfolio).permit(:title, :subtitle, :thumbnail, :main_image, :body, technologies_attributes: [:name])
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def portfolio_img img, type
    if img
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_with(model: @portfolio_item, local: true) do |form| %>

<div class="row">
  <div class="col-md-6">
    <div class="form_group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control form-bottom-space' %>
    </div>

    <div class="form_group">
      <%= form.label :subtitle %>
      <%= form.text_field :subtitle, class: 'form-control form-bottom-space' %>
    </div>

    <div class="form_group">
      <label class="btn btn-primary">
        Upload main image file <%= form.file_field :main_image, style: "display: none;" %>
      </label>
    </div>

    <div class="form_group">
      <label class="btn btn-primary">
        Upload thumbnail image file <%= form.file_field :thumbnail, style: "display: none;" %>
      </label>
    </div>

  </div>
  <div class="col-md-6">
    <div class="form_group">
      <%= form.label :body %>
      <%= form.text_area :body, class: 'form-control form-bottom-space', rows: 15 %>
    </div>
  </div>
  <div class="col-md-12">

    <hr>
    <h3>Technologies</h3>
    <div>
      <%= form.fields_for :technologies do |technology_form| %>
      <div class="form_group">
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name, class: 'form-control form-bottom-space' %>
      </div>
      <% end %>
    </div>

  </div>
</div>



<div class="form_group">
  <%= form.submit class: 'btn btn-outline-primary btn-block' %>
</div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4" data-id="<%= portfolio_item.id %>">
  <div class="card mb-4 shadow-sm">
    <%= image_tag portfolio_img(portfolio_item.thumbnail.url, 'thumb'),  width: '100%' %>
    <div class="card-body">
      <p class="card-text">
        <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span>
        <p><%= portfolio_item.subtitle %></p>
        <p><%= portfolio_item.body %></p>
        <%= link_to 'Edit', edit_portfolio_path(portfolio_item) if logged_in?(:admin) %>
        <%= link_to 'Delete portfolio_item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:admin) %>
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></button>
          <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
        </div>
        <small class="text-muted">9 mins</small>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/edit.html.erb
<div class="container portfolio-padding portfolio-container">
  <h1>Edit this project item</h1>

  <%= render 'form', portfolio_item: portfolios_path if logged_in?(:admin) %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row <%= "sortable" if logged_in?(:admin) %>">
      <!-- <%= link_to 'New project item', new_portfolio_path if logged_in?(:admin) %> -->
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-padding portfolio-container">
  <h1>Create a new project item</h1>
  <%= render 'form', portfolio: @portfolio_item if logged_in?(:admin) %>
</div>

app/views/portfolios/rails.html.erb
<h1>Rails projects</h1>

<%= link_to 'New project item', new_portfolio_path if logged_in?(:admin) %>

<h1>Projects</h1>
<% @rails_items.each do |project| %>
  <p /><%= link_to project.title, portfolio_show_path(project) %>
  <p /><%= project.subtitle %>
  <p /><%= project.body %>
  <p /><%= image_tag project.thumbnail unless project.thumbnail.nil? %>
  <%= link_to 'Edit', edit_portfolio_path(project) if logged_in?(:admin) %>
  <%= link_to 'Delete project', project, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:admin) %>
<% end %>

app/views/portfolios/show.html.erb
<div class="container portfolio-padding portfolio-container">
  <div class="row">

    <div class="col-md-7">
      <%= image_tag portfolio_img(@portfolio_item.main_image.url, 'main'), width: '100%' %>
    </div>

    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>
      <hr>
      <p>
        <em><%= @portfolio_item.subtitle %></em>
      </p>

      <p>
        <%= @portfolio_item.body %>
      </p>


      <h3>Technologies Used:</h3>
      <p>
        <% @portfolio_item.technologies.each do |tech| %>
        <p><%= tech.name %></p>
        <% end %>
      </p>

    </div>

  </div>
</div>