config/routes.rb
Rails.application.routes.draw do
  # path: '' so that it won't show as /users/login but as /login
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'rails-projects', to: 'portfolios#rails'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :change_status
    end
  end
  root 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p class="app-footer"><%= copyright_generator_helper %></p>
  </div>
  <%= session_source_helper %>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Ayesha W.</h3>
    <nav class="nav nav-masthead justify-content-center ">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
  <footer class="blog-footer">
    <p><%= copyright_generator_helper %></p>
    <p>
      <a href="#">Back to top</a>
    </p>
  </footer>

app/views/shared/_blog_header.html.erb
    <header class="blog-header py-3">
      <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">
        </div>
        <div class="col-4 text-center">
          <%= link_to 'Other side', root_path, class: 'blog-header-logo text-dark' %>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
          <%= login_helper 'btn btn-sm btn-outline-secondary' %>
        </div>
      </div>
    </header>

app/views/shared/_blog_nav.html.erb
<div class="nav-scroller py-1 mb-2">
  <nav class="nav d-flex justify-content-between">
    <%= nav_helper 'p-2 text-muted', 'span' %>
    <!-- <%= link_to "Home", root_path, class: 'p-2 text-muted' %>
    <%= link_to "About", about_path, class: 'p-2 text-muted' %>
    <%= link_to "Contact", contact_path, class: 'p-2 text-muted' %>
    <%= link_to "Blog", blogs_path, class: 'p-2 text-muted' %>
    <%= link_to "Portfolio", portfolios_path, class: 'p-2 text-muted' %> -->
  </nav>
</div>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-4 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>

  <div class="p-4">
    <h4 class="font-italic">Elsewhere</h4>
    <p class="list-unstyled social-media-links">
      <a href="#"><%= fa_icon "github", base: "square-o" %></a>
      <a href="#"><%= fa_icon "twitter", base: "square-o" %></a>
      <a href="#"><%= fa_icon "instagram", base: "square-o" %></a>
    </p>
  </div>
</aside><!-- /.blog-sidebar -->

app/views/shared/_feature_post.html.erb
<div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
  <div class="col-md-6 px-0">
    <h1 class="display-4 font-italic">Title of a longer featured blog post</h1>
    <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.</p>
    <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path, class: 'nav-link active' %></div>
  <div><%= link_to "About", about_path, class: 'nav-link' %></div>
  <div><%= link_to "Contact", contact_path, class: 'nav-link' %></div>
  <div><%= link_to "Blog", blogs_path, class: 'nav-link' %></div>
  <div><%= link_to "Portfolio", portfolios_path, class: 'nav-link' %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to 'View all portfolios', portfolios_path unless action_name == 'index' %>
      <%= " / ".html_safe unless action_name == 'index' %>
      <a href="#">Back to top</a>
    </p>
    <p><%= copyright_generator_helper %></p>
  </div>
</footer>

app/views/shared/_portfolio_jumbotron.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>Album portfolio</h1>
    <p class="lead text-muted">Here's a collection of some previous projects that I did in my own time.
      I also put current project here and may occasionally share my thoughts or
      learning experience while working on my current project on my blog.
    </p>
      <p>
        <%= link_to "About", about_path, class: "btn btn-primary my-2" %>
        <%= link_to "Blog", blogs_path, class: "btn btn-secondary my-2" %>
      </p>
    </div>
  </section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-md-7 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
      </div>
      <div class="col-sm-4 offset-md-1 py-4">
        <h4 class="text-white">Go to...</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/new.html.erb
<h1>Create a new project item</h1>

<%= render 'form', portfolio: @portfolio_item if logged_in?(:admin) %>