config/routes.rb
Rails.application.routes.draw do
  # path: '' so that it won't show as /users/login but as /login
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'rails-projects', to: 'portfolios#rails'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :change_status
    end
  end
  root 'pages#home'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="keywords" content="<%= @seo_keywords %>" />

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <div id="background"></div>
    <%= render 'shared/application_nav' %>
    <%= yield %>
    <%= render 'shared/application_footer' %>

  </div>
</body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="keywords" content="<%= @seo_keywords %>" />

  <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container">

    <%= render 'shared/blog_header' %>

    <%= render 'shared/blog_nav' %>

    <%= render 'shared/feature_post' if action_name == 'index' %>

  </div>

  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8 blog-main">
        <h4 class="pb-4 mb-4 font-italic border-bottom">
          <p><%= link_to 'New Blog', new_blog_path if logged_in?(:admin) unless action_name == 'new' %></p>
        </h4>

        <%= yield %>

        <%= session_source_helper %>
      </div><!-- /.blog-main -->

      <%= render 'shared/blog_sidebar' %>

    </div><!-- /.row -->

  </main><!-- /.container -->

  <%= render 'shared/blog_footer' %>

</body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= stylesheet_link_tag    'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>

    <%= render 'shared/portfolio_nav' %>

      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
            <strong>Album</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <%= render 'shared/portfolio_jumbotron.html.erb' unless logged_in?(:admin) %>

      <%= yield %>

    </main>

    <%= render 'shared/portfolio_footer.html.erb' %>

    <%= session_source_helper %>

  </body>
</html>